name: Django CI/CD Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: 🏗️ Build & Install
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:15
        env:
          POSTGRES_DB: django_db
          POSTGRES_USER: django_user
          POSTGRES_PASSWORD: django_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U django_user -d django_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgres://django_user:django_pass@localhost:5432/django_db
      DJANGO_SETTINGS_MODULE: django_devops_lab.settings
      PYTHONUNBUFFERED: 1

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Lint and Security Scan
        run: |
          echo "🧹 Running flake8 and bandit scans..."
          flake8 .
          bandit -r . || true  # don't fail pipeline for bandit warnings

      - name: Wait for DB
        run: |
          echo "⏳ Waiting for PostgreSQL..."
          for i in {1..10}; do
            nc -z localhost 5432 && echo "Database is ready!" && break
            echo "Waiting for database..."
            sleep 5
          done

      - name: Run Migrations and Tests
        run: |
          python manage.py migrate --noinput
          python manage.py test

      - name: 🐳 Build Docker image
        run: |
          docker build -t ${{ github.repository }}:latest .

      - name: 🚀 Deploy to Docker Hub (only on main)
        if: github.ref == 'refs/heads/main' && success()
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          docker tag ${{ github.repository }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/django-devops-lab:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/django-devops-lab:latest
